<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Chaipoints-MacBook-Air.local" name="decimalModuleId" tests="1" failures="1" timestamp="8 Jan 2020 09:55:42 GMT" time="0.232" errors="0">
  <testcase name="testBadRequest" time="0.226" classname="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
    <failure type="java.lang.AssertionError" message="Status expected:&amp;lt;400 BAD_REQUEST&amp;gt; but was:&amp;lt;200 OK&amp;gt;

&amp;gt; POST https://testing.chaipoint.com/qa3/outlet-pos-api/api/order/history
&amp;gt; WebTestClient-Request-Id: [1]
&amp;gt; service.auth.key: [1234567]
&amp;gt; Content-Type: [application/json]
&amp;gt; Content-Length: [23]

{
  &amp;quot;moduleId&amp;quot;:1.5990
}

&amp;lt; 200 OK OK
&amp;lt; Date: [Wed, 08 Jan 2020 09:55:38 GMT]
&amp;lt; Content-Type: [application/json;charset=UTF-8]
&amp;lt; Transfer-Encoding: [chunked]
&amp;lt; Connection: [keep-alive]
&amp;lt; Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
&amp;lt; Access-Control-Allow-Credentials: [true]
&amp;lt; Access-Control-Max-Age: [86400]
&amp;lt; X-Content-Type-Options: [nosniff]
&amp;lt; X-XSS-Protection: [1; mode=block]
&amp;lt; Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
&amp;lt; Pragma: [no-cache]
&amp;lt; Expires: [0]
&amp;lt; X-Frame-Options: [DENY]

{&amp;quot;errorCode&amp;quot;:&amp;quot;INTERNAL_ERROR_OCCURED&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot; Could not fetch orders&amp;quot;}
">
      <![CDATA[java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<200 OK>

> POST https://testing.chaipoint.com/qa3/outlet-pos-api/api/order/history
> WebTestClient-Request-Id: [1]
> service.auth.key: [1234567]
> Content-Type: [application/json]
> Content-Length: [23]

{
  "moduleId":1.5990
}

< 200 OK OK
< Date: [Wed, 08 Jan 2020 09:55:38 GMT]
< Content-Type: [application/json;charset=UTF-8]
< Transfer-Encoding: [chunked]
< Connection: [keep-alive]
< Access-Control-Allow-Headers: [Content-Type, Cookie, service.auth.key]
< Access-Control-Allow-Credentials: [true]
< Access-Control-Max-Age: [86400]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1; mode=block]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Frame-Options: [DENY]

{"errorCode":"INTERNAL_ERROR_OCCURED","message":" Could not fetch orders"}

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testBadRequest(TestErrorsForPostReq.java:86)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
Caused by: java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<200 OK>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testBadRequest -->
</testsuite> <!-- decimalModuleId -->
