<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" total="7" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="catalogue-master-getProductCatalogue" duration-ms="61622" started-at="2019-12-04T12:47:01Z" finished-at="2019-12-04T12:48:03Z">
    <groups>
    </groups>
    <test name="validParameters" duration-ms="30781" started-at="2019-12-04T12:47:01Z" finished-at="2019-12-04T12:47:32Z">
      <class name="cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg@13b6aecc]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="35" started-at="2019-12-04T18:17:01Z" finished-at="2019-12-04T18:17:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg@13b6aecc]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="24322" started-at="2019-12-04T18:17:01Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:17:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg@13b6aecc]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="2" started-at="2019-12-04T18:17:25Z" finished-at="2019-12-04T18:17:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg.testGetProductCatalogue(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="testGetProductCatalogue(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg@13b6aecc]" name="testGetProductCatalogue" duration-ms="6384" started-at="2019-12-04T18:17:25Z" finished-at="2019-12-04T18:17:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234567]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/validParameters.json]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1, 2, 3, 4]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[220, 220, 220, 220]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg.testGetProductCatalogue(TestGetProductCatalogueApiTestNg.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetProductCatalogue -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg@13b6aecc]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:32Z" finished-at="2019-12-04T18:17:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg.testGetProductCatalogue(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg@13b6aecc]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:32Z" finished-at="2019-12-04T18:17:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- cool.fountain.online.web.test.catalogue.master.TestGetProductCatalogueApiTestNg -->
    </test> <!-- validParameters -->
    <test name="emptypayload" duration-ms="214" started-at="2019-12-04T12:47:37Z" finished-at="2019-12-04T12:47:37Z">
      <class name="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6ab778a]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:37Z" finished-at="2019-12-04T18:17:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6ab778a]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="9" started-at="2019-12-04T18:17:37Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:17:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="FAIL" signature="testErrorCode(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6ab778a]" name="testErrorCode" duration-ms="200" started-at="2019-12-04T18:17:37Z" finished-at="2019-12-04T18:17:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234567]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/TerminalIdNotInDb.json]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[INVALID_REQUEST]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> WebTestClient-Request-Id: [1]
> Content-Length: [28]
> service.auth.key: [1234567]
> Content-Type: [application/json]

{
  "terminalId": "999888"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:37 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> WebTestClient-Request-Id: [1]
> Content-Length: [28]
> service.auth.key: [1234567]
> Content-Type: [application/json]

{
  "terminalId": "999888"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:37 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(TestErrorsForPostReq.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorCode -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6ab778a]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:37Z" finished-at="2019-12-04T18:17:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6ab778a]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:37Z" finished-at="2019-12-04T18:17:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6ab778a]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:37Z" finished-at="2019-12-04T18:17:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- cool.fountain.online.web.test.errors.TestErrorsForPostReq -->
    </test> <!-- emptypayload -->
    <test name="TerminalIdNotInDb" duration-ms="80" started-at="2019-12-04T12:47:42Z" finished-at="2019-12-04T12:47:42Z">
      <class name="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@762ef0ea]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:42Z" finished-at="2019-12-04T18:17:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@762ef0ea]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:42Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:17:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="FAIL" signature="testErrorCode(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@762ef0ea]" name="testErrorCode" duration-ms="72" started-at="2019-12-04T18:17:42Z" finished-at="2019-12-04T18:17:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234567]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/TerminalIdNotInDb.json]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[INVALID_TERMINAL_ID]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> WebTestClient-Request-Id: [1]
> Content-Length: [28]
> service.auth.key: [1234567]
> Content-Type: [application/json]

{
  "terminalId": "999888"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:42 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> WebTestClient-Request-Id: [1]
> Content-Length: [28]
> service.auth.key: [1234567]
> Content-Type: [application/json]

{
  "terminalId": "999888"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:42 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(TestErrorsForPostReq.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorCode -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@762ef0ea]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:42Z" finished-at="2019-12-04T18:17:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@762ef0ea]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:42Z" finished-at="2019-12-04T18:17:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@762ef0ea]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:42Z" finished-at="2019-12-04T18:17:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- cool.fountain.online.web.test.errors.TestErrorsForPostReq -->
    </test> <!-- TerminalIdNotInDb -->
    <test name="nullTerminalId" duration-ms="190" started-at="2019-12-04T12:47:47Z" finished-at="2019-12-04T12:47:47Z">
      <class name="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6a2b953e]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:47Z" finished-at="2019-12-04T18:17:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6a2b953e]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:47Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:17:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6a2b953e]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:47Z" finished-at="2019-12-04T18:17:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="testErrorCode(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6a2b953e]" name="testErrorCode" duration-ms="182" started-at="2019-12-04T18:17:47Z" finished-at="2019-12-04T18:17:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234567]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/nullTerminalId.json]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[INVALID_TERMINAL_ID]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> WebTestClient-Request-Id: [1]
> service.auth.key: [1234567]
> Content-Type: [application/json]
> Content-Length: [23]

{
  "terminalId":null
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:47 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> WebTestClient-Request-Id: [1]
> service.auth.key: [1234567]
> Content-Type: [application/json]
> Content-Length: [23]

{
  "terminalId":null
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:47 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(TestErrorsForPostReq.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorCode -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6a2b953e]" name="springTestContextAfterTestClass" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:47Z" finished-at="2019-12-04T18:17:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@6a2b953e]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:47Z" finished-at="2019-12-04T18:17:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
      </class> <!-- cool.fountain.online.web.test.errors.TestErrorsForPostReq -->
    </test> <!-- nullTerminalId -->
    <test name="emptyTerminalId" duration-ms="74" started-at="2019-12-04T12:47:52Z" finished-at="2019-12-04T12:47:52Z">
      <class name="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@5609159b]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:52Z" finished-at="2019-12-04T18:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@5609159b]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="2" started-at="2019-12-04T18:17:52Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="FAIL" signature="testErrorCode(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@5609159b]" name="testErrorCode" duration-ms="66" started-at="2019-12-04T18:17:52Z" finished-at="2019-12-04T18:17:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234567]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/emptyTerminalId.json]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[INVALID_TERMINAL_ID]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> Content-Length: [21]
> WebTestClient-Request-Id: [1]
> service.auth.key: [1234567]
> Content-Type: [application/json]

{
  "terminalId":""
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:52 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> Content-Length: [21]
> WebTestClient-Request-Id: [1]
> service.auth.key: [1234567]
> Content-Type: [application/json]

{
  "terminalId":""
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:52 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isBadRequest(StatusAssertions.java:131)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(TestErrorsForPostReq.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<400 BAD_REQUEST> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorCode -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@5609159b]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:52Z" finished-at="2019-12-04T18:17:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@5609159b]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:52Z" finished-at="2019-12-04T18:17:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testErrorCode(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@5609159b]" name="springTestContextAfterTestClass" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:52Z" finished-at="2019-12-04T18:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- cool.fountain.online.web.test.errors.TestErrorsForPostReq -->
    </test> <!-- emptyTerminalId -->
    <test name="emptyServiceAuthKey" duration-ms="75" started-at="2019-12-04T12:47:57Z" finished-at="2019-12-04T12:47:57Z">
      <class name="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@3e96bacf]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:57Z" finished-at="2019-12-04T18:17:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@3e96bacf]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:57Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:17:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@3e96bacf]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:57Z" finished-at="2019-12-04T18:17:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testServiceAuthKey(java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="testServiceAuthKey(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@3e96bacf]" name="testServiceAuthKey" duration-ms="68" started-at="2019-12-04T18:17:57Z" finished-at="2019-12-04T18:17:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/validParameters.json]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status expected:<403 FORBIDDEN> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> Content-Length: [31]
> WebTestClient-Request-Id: [1]
> Content-Type: [application/json]
> service.auth.key: []

{
  "terminalId":"terminal_1"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:57 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status expected:<403 FORBIDDEN> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> Content-Length: [31]
> WebTestClient-Request-Id: [1]
> Content-Type: [application/json]
> service.auth.key: []

{
  "terminalId":"terminal_1"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:47:57 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isForbidden(StatusAssertions.java:146)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testServiceAuthKey(TestErrorsForPostReq.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<403 FORBIDDEN> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testServiceAuthKey -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@3e96bacf]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="1" started-at="2019-12-04T18:17:57Z" finished-at="2019-12-04T18:17:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testServiceAuthKey(java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@3e96bacf]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:17:57Z" finished-at="2019-12-04T18:17:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- cool.fountain.online.web.test.errors.TestErrorsForPostReq -->
    </test> <!-- emptyServiceAuthKey -->
    <test name="invalidServiceAuthKey" duration-ms="122" started-at="2019-12-04T12:48:02Z" finished-at="2019-12-04T12:48:03Z">
      <class name="cool.fountain.online.web.test.errors.TestErrorsForPostReq">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@f2ff811]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2019-12-04T18:18:02Z" finished-at="2019-12-04T18:18:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@f2ff811]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="1" started-at="2019-12-04T18:18:02Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2019-12-04T18:18:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@f2ff811]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:18:02Z" finished-at="2019-12-04T18:18:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testServiceAuthKey(java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="testServiceAuthKey(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@f2ff811]" name="testServiceAuthKey" duration-ms="113" started-at="2019-12-04T18:18:02Z" finished-at="2019-12-04T18:18:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[/api/catalogue-master/getProductCatalogue]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test-files/json-data/catalogue-master/getProductCatalogue/validParameters.json]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status expected:<403 FORBIDDEN> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> Content-Length: [31]
> service.auth.key: [123]
> WebTestClient-Request-Id: [1]
> Content-Type: [application/json]

{
  "terminalId":"terminal_1"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:48:03 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status expected:<403 FORBIDDEN> but was:<404 NOT_FOUND>

> POST https://qa3-api.chaipoint.com/outlet-pos-api/api/catalogue-master/getProductCatalogue
> Content-Length: [31]
> service.auth.key: [123]
> WebTestClient-Request-Id: [1]
> Content-Type: [application/json]

{
  "terminalId":"terminal_1"
}

< 404 NOT_FOUND Not Found
< Date: [Wed, 04 Dec 2019 12:48:03 GMT]
< Content-Type: [text/html;charset=utf-8]
< Content-Length: [1102]
< Connection: [keep-alive]
< Server: [Apache-Coyote/1.1]
< Content-Language: [en]

<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.0 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /outlet-pos-api/api/catalogue-master/getProductCatalogue</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/outlet-pos-api/api/catalogue-master/getProductCatalogue</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.5.0</h3></body></html>

	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.StatusAssertions.isForbidden(StatusAssertions.java:146)
	at cool.fountain.online.web.test.errors.TestErrorsForPostReq.testServiceAuthKey(TestErrorsForPostReq.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Status expected:<403 FORBIDDEN> but was:<404 NOT_FOUND>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:227)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testServiceAuthKey -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@f2ff811]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2019-12-04T18:18:03Z" finished-at="2019-12-04T18:18:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cool.fountain.online.web.test.errors.TestErrorsForPostReq.testServiceAuthKey(java.lang.String,java.lang.String,java.lang.String) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.json.JSONException,org.json.simple.parser.ParseException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:cool.fountain.online.web.test.errors.TestErrorsForPostReq@f2ff811]" name="springTestContextAfterTestClass" is-config="true" duration-ms="1" started-at="2019-12-04T18:18:03Z" finished-at="2019-12-04T18:18:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- cool.fountain.online.web.test.errors.TestErrorsForPostReq -->
    </test> <!-- invalidServiceAuthKey -->
  </suite> <!-- catalogue-master-getProductCatalogue -->
</testng-results>
